export const G20_COUNTRIES_PT_EN = [
  "South Africa",
  "Germany",
  "Saudi Arabia",
  "Argentina",
  "Australia",
  "Brazil",
  "Canada",
  "China",
  "South Korea",
  "United States",
  "France",
  "India",
  "Indonesia",
  "Italy",
  "Japan",
  "Mexico",
  "United Kingdom",
  "Russia",
  "Turkey",
];
